### ISSUE TITLE
Improved campaign creation user experience

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#11]
Campaign creation is currently very flexibly but difficult to use for non-technical users.
- [ ] Present a concept for how this change might look to @levelos

**Comment by unclegcb** [comment]
@ruscoe - 
This is an old ticket that we never walked through: updating for the current rewrite. Assigning to you for now although depending on how things proceed you may not be responsible for this piece.

**Comment by ruscoe** [comment]
Design changes described in these tickets:
https://github.com/thinkshout/mailchimp/issues/26
https://github.com/thinkshout/mailchimp/issues/27

**Comment by ruscoe** [comment]
Closing along with #26 and #27
