### ISSUE TITLE
Replace all instances of module_invoke_all()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#117]
Replace with [ModuleHandler::invokeAll](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Extension!ModuleHandler.php/function/ModuleHandler%3A%3AinvokeAll/8)

**Comment by levelos** [comment]
Got this one. 9ab1637.

**Comment by unclegcb** [comment]
Well, so did I! But mine works better because you have to do some goofy stuff in .api.php. ;)
https://github.com/thinkshout/mailchimp/pull/151
