### ISSUE TITLE
Replace all instances of drupal_alter()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#121]
Replace with [ModuleHandler::alter](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21ModuleHandler.php/function/ModuleHandler%3A%3Aalter/8)

**Comment by jamidwyer** [comment]
Fixed by lev in commit f0cbb67d354fcab0a3a27c04e8533296a6c18784.
