### ISSUE TITLE
db_drop_table in mailchimp_lists_update_7204 throws sql exception

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#13]
Check out 7.x-2.x, run the update against a 7.x-2.10 configuration.

the line "db_drop_table('mailchimp_lists', 'list_type');" successfully drops the table but then crashes the update with:

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.list_type' in 'field list': SELECT base.id AS id, base.name AS name, base.mc_list_id AS mc_list_id, base.label AS label, base.description AS description, base.list_type AS list_type, base.settings AS settings, base.status AS status, base.module AS module, base.created AS created, base.updated AS updated FROM {mailchimp_lists} base; Array ( ) in EntityAPIController->query() (line 187 of /Users/gcb/projects/mailchimp_test/drupal/profiles/mailchimp_dev/modules/contrib/entity/includes/entity.controller.inc).

**Comment by levelos** [comment]
I tried recreating several times with no luck.

My process was to:
- checkout 7.x-2.10
- run `drush si mailchimp_dev`
- checkout 7.x-2.x
- run `drush updatedb`

If you can consistently recreate, try add this call `drupal_get_schema('mailchimp_lists', TRUE)` after the db change.

**Comment by unclegcb** [comment]
Interesting.

I also have no problem when I use drush.
When using update.php, I get the same error.
After I add the drupal_get_schema, the error goes away with update.php.

I was trying a different API call to reset the cache: so you gave me the right one and it solved this issue too. Thanks!
