### ISSUE TITLE
Review caching code in 3.x

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#16]
I've restructured the cacheing because we were previously using a mix of a custom cache and the system cache: now using all custom caches. Concerned that I might be missing some best practice. Just check out the cache_get and cache_set calls in mailchimp.module.

**Comment by levelos** [comment]
One bug a few minor issues. See
- 529fba1fd430d8f0d9f515441797ae3b45601817
- f0a058bd2cbbb76b6d3cb7b20b396fd4f4ad825c
- a009572136b5b6f7d21bc7a194b4dddd630d35e6 (the bug)
