### ISSUE TITLE
Review exception handling in mailchimp.module api wrappers

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#17]
Currently catching all these and logging with watchdog calls. Not sure this is the best choice. Could also have a flag on all these calls that allows the exception through, or just throw the exception up to be dealt with at the next level.

**Comment by levelos** [comment]
I'm not sure of the necessity, but since the code's already written, I definitely see no need to revert any of it. I did add a few missing default values that were only set inside the try block.
