### ISSUE TITLE
Update tests to work with new MC library

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#182]
- [x] D7
- [ ] D8

D8 tasks
- [x] Update `mailchimp_get_api_object()` to load test classes when test mode is enabled.
  - [D7 example](https://github.com/thinkshout/mailchimp/blob/7.x-3.x-api-v3/mailchimp.module#L140-L145)
- [x] Port `mailchimp_campaign` module tests from D7
  - [D7 tests](https://github.com/thinkshout/mailchimp/blob/7.x-3.x-api-v3/modules/mailchimp_campaign/tests/mailchimp_campaigns.test)
  - [D8 tests](https://github.com/thinkshout/mailchimp/tree/8.x-1.x-api-v3/modules/mailchimp_lists/src/Tests)
- [x] Port `mailchimp_lists` module tests from D7
  - [D7 tests](https://github.com/thinkshout/mailchimp/blob/7.x-3.x-api-v3/modules/mailchimp_lists/tests/mailchimp_lists.test)
  - [D8 tests](https://github.com/thinkshout/mailchimp/tree/8.x-1.x-api-v3/modules/mailchimp_campaign/src/Tests)
- [x] Remove old test modules (entire directory)
  - [mailchimp_campaign_test](https://github.com/thinkshout/mailchimp/tree/8.x-1.x-api-v3/modules/mailchimp_campaign/tests/modules/mailchimp_campaign_test)
  - [mailchimp_lists_test](https://github.com/thinkshout/mailchimp/tree/8.x-1.x-api-v3/modules/mailchimp_lists/tests/modules/mailchimp_lists_test)

**Comment by amydecat** [comment]
Test tasks are finished. :tada:
