### ISSUE TITLE
Update documentation for new MC library

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#183]
- [x] D7
- [x] D8

Update any documentation referring to the old MC library. You'll find a bunch of stuff if you search for "Wrapper around MCAPI->"

**Comment by amydecat** [comment]
Assigning to you, @ruscoe, in case you'd like to double check my work. 😄

**Comment by ruscoe** [comment]
Just missing `()` on this line:
https://github.com/thinkshout/mailchimp/commit/c3c54b4661f59b42f3262b3a75d51930a457f93f#diff-bb0d240e8bb9e959c6e84bae87e337d4R257

**Comment by amydecat** [comment]
Helps if I put the correct library function in there too :wink:

**Comment by ruscoe** [comment]
👍
