### ISSUE TITLE
Deprecated D8 functions

### ISSUE THREAD

**Issue by amydecat** [thinkshout/mailchimp#188]
- [ ] entity_create
- [ ] entity_load_multiple
- [ ] entityManager
- [x] check_plain
- [x] l()
- [x] drupal_render

**Comment by ruscoe** [comment]
Adding that `Drupal::entityManager()->getDefinitions()` should be replaced with `Drupal::entityTypeManager()->getDefinitions();`

**Comment by amydecat** [comment]
`drupal_render()` appears to be replaced with `\Drupal::service('renderer')->render`. https://api.drupal.org/api/drupal/core!includes!common.inc/function/drupal_render/8

@ruscoe: I believe this is working, but could always use extra eyes. The places where `drupal_render` needed to be replaced was in `MailchimpCampaignForm.php`.

**Comment by amydecat** [comment]
Pausing on this task for now. The functions are currently working in D8 and will be deprecated in D9 (~5 yrs time). Also, there is a scarcity of good alternatives to some of these so early in D8's existence.

**Comment by mortenson** [comment]
I'm closing this out - we'll address deprecation notices on Drupal.org as they come up.
