### ISSUE TITLE
Sending campaigns

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#194]
D7: https://github.com/thinkshout/mailchimp/blob/7.x-3.x-api-v3/modules/mailchimp_campaign/mailchimp_campaign.module#L415

D8: https://github.com/thinkshout/mailchimp/blob/8.x-1.x-api-v3/modules/mailchimp_campaign/mailchimp_campaign.module#L169

**Comment by amydecat** [comment]
Assigning to @ruscoe to check my work.

**Comment by ruscoe** [comment]
Looks good.
