### ISSUE TITLE
consider grouping by list

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#2]
Would require refactoring `mailchimp_lists_activity_page()`. But seems the list is an important piece of info we're missing.

**Comment by unclegcb** [comment]
Started to look at this and realized it would make sense to just have the whole table be column-sortable. From what I can tell, this means I have to insert the data into sql or write all my own routines? And that means building out a schema for "actions". Sound like the thing to do?

**Comment by levelos** [comment]
Sortable columns are a pain for non-SQL data. Don't worry about it for now. But grouping by list probably still makes sense.

**Comment by unclegcb** [comment]
Do you mean using grouping as the primary sort on the table or creating separate tables for each list?

**Comment by levelos** [comment]
The former. Group by list, sort by date.

**Comment by unclegcb** [comment]
This change has been pushed to Git. I left the old sort algorithm in the .module for now... maybe it'll be useful?
