### ISSUE TITLE
Signup forms need testing

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#202]
- [x] Test signup form page
- [x] Test signup form block
- [x] Test signup form on user edit tab

**Comment by amydecat** [comment]
The signup form on the block is working. The subscribe button on a Drupal user's edit page is fully functional, however it's throwing a 404 error at this point in the code: https://github.com/thinkshout/mailchimp-api-php/blob/master/src/Mailchimp.php#L262

It's going here: https://github.com/thinkshout/mailchimp/blob/8.x-1.x-api-v3/modules/mailchimp_lists/mailchimp_lists.module#L170

And `$ret` is returning as `NULL`, so it's outputting the warning "There was a problem with your newsletter signup.". @ruscoe, I could probably use your assistance debugging this one. Good news is that it's working, just throwing this erroneous error as you mentioned previously. :smile:
