### ISSUE TITLE
Campaigns cannot be viewed

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#206]
`Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'canonical' found for the 'mailchimp_campaign' entity type in Drupal\Core\Entity\Entity->toUrl() (line 219 of /Users/ruscoe/Sites/mandrill8/core/lib/Drupal/Core/Entity/Entity.php).`

**Comment by ruscoe** [comment]
Dev environment issue most likely.

**Comment by karamveer-cipl** [comment]
Hello Ruscoe,

I am also facing same issue,please let me know how to fix this?

FYI below is errors->
The website encountered an unexpected error. Please try again later.

Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'canonical' found for the 'mailchimp_campaign' entity type in Drupal\Core\Entity\Entity->toUrl() (line 214 of core/lib/Drupal/Core/Entity/Entity.php).

Drupal\Core\Entity\Entity->urlInfo() (Line: 577)
content_translation_page_attachments(Array) (Line: 297)
Drupal\Core\Render\MainContent\HtmlRenderer->invokePageAttachmentHooks(Array) (Line: 273)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 98)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 77)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 626)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

thanks,
Karamveer

**Comment by mortenson** [comment]
I just double checked and the mailchimp_campaign does have have a canonical link template now. Closing this out.
