### ISSUE TITLE
Saved "Content Sections" on campaigns not auto-populating with previously saved content.

### ISSUE THREAD

**Issue by amydecat** [thinkshout/mailchimp#207]
The fields are not present either. AJAX issue, as well?

**Comment by ruscoe** [comment]
`mailchimp_campaign_save_campaign()` needs to send the content sections in a separate API call. See D7 code here:

https://github.com/thinkshout/mailchimp/blob/7.x-3.x-api-v3/modules/mailchimp_campaign/mailchimp_campaign.module#L356

**Comment by amydecat** [comment]
Fixed! 💃
