### ISSUE TITLE
Updating a subscription from a user profile works but gives the message "There was a problem with your newsletter signup."

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#214]

**Comment by ruscoe** [comment]
@AmyVS I think this is broken in D8 as well. Check out this commit for a fix: https://github.com/thinkshout/mailchimp/commit/794fb644e329ade092e348a7fca43650acae6bfb

**Comment by amydecat** [comment]
This is wrapped up for D8.
