### ISSUE TITLE
Call to hasTranslation() on a non-object when saving campaigns

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#218]
`Fatal error: Call to a member function hasTranslation() on a non-object in /Users/ruscoe/Sites/mc8/core/lib/Drupal/Core/Field/Plugin/Field/FieldType/ChangedItem.php on line 52`

I fixed it with [this commit](https://github.com/thinkshout/mailchimp/commit/db6fd8b080af53fb8ad8f4264c9ebc6366b41d26), which is just the same functionality using different entity and form methods.

I don't know exactly why it stopped working last week, but `$existing_campaign_id` was not being set. This was causing a new campaign to be created in MailChimp, returning a new campaign ID. This caused a problem when saving the entity, as Drupal knew the entity was not new but the original and current IDs didn't match.

We need a 8.x-1.1 release from the 8.x-1.x branch. We can include any other fixes you made last week.

**Comment by mortenson** [comment]
:wave: I'm closing this out, we can revisit the fix in new bug reports on Drupal.org
