### ISSUE TITLE
Drupal.org info and docs

### ISSUE THREAD

**Issue by amydecat** [thinkshout/mailchimp#221]
# Getting Drupal.org pages up-to-date

---

Here's the [documentation](https://docs.google.com/a/thinkshout.com/document/d/1uA8fOsMZZSy-4lV5Y9tK7RyRnWGew4DCg41bQMIxU_Y/edit?usp=sharing) regarding upgrading from MailChimp 7.x-2.x to 4.x
## Screenshots of current Drupal.org pages, and notes:

![mc_drupal_page1](https://cloud.githubusercontent.com/assets/6893715/17821009/4ce7d12a-6604-11e6-8d36-1a4565e400d1.png)
![mc_drupal_page2](https://cloud.githubusercontent.com/assets/6893715/17821247/82d12eb6-6605-11e6-9682-b0e2f5310284.png)
![mc_drupal_page3](https://cloud.githubusercontent.com/assets/6893715/17821014/53c0f102-6604-11e6-9350-75d568430f3d.png)
![mc_drupal_page4](https://cloud.githubusercontent.com/assets/6893715/17821022/5610223e-6604-11e6-8fed-5678f0f19677.png)
## Additional work
- [x] Create an FAQ page for the MailChimp module
- [x] Deprecating 7.x-3.x?

**Comment by ruscoe** [comment]
Project page needs to be updated to reflect 3.x being deprecated. Probably by me.
