### ISSUE TITLE
This repository is not in sync with D.O

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp#228]
This repo needs updating.

**Comment by ruscoe** [comment]
Latest commits on 7.x-4.x are in sync between d.o and github:

https://github.com/thinkshout/mailchimp/commit/73e33acf1f82bf0e3e5e0b250e7e4db952c764ca

http://cgit.drupalcode.org/mailchimp/commit/?id=73e33ac

Is it a different branch?

**Comment by taz77** [comment]
For some reason when I looked at the repo it was out of sync. I noticed yesterday that it was up to date. Closing this.
