### ISSUE TITLE
Document breaking change in mailchimp_signup_subscribe_form_submit()

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#233]
See issue: https://www.drupal.org/node/2833376

In `mailchimp_signup_subscribe_form_submit()`, `$form_state['mailchimp_results']` is now `$form_state['mailchimp_results'][$list_id]`

The variable only exists to be used in form alter hooks. This change will break any existing integration using the variable and needs to be documented in the 7.x-4.9 release notes.

**Comment by mortenson** [comment]
Closing as outdated.
