### ISSUE TITLE
Hidden Interest Groups are completely ignored

### ISSUE THREAD

**Issue by taz77** [thinkshout/mailchimp#238]
This issue and patches, https://www.drupal.org/project/mailchimp/issues/2839768, has created a problem where hidden interest groups cannot be retrieved in Drupal (API library returns them no problem). The inability to process hidden interests groups will break certain marketing workflows. It is better if there is an option to return hidden interests groups with a default of not returning them.

**Comment by mortenson** [comment]
Closing this out - see comment at https://github.com/thinkshout/mailchimp/pull/239#issuecomment-447510736 for details.
