### ISSUE TITLE
Drupalize "Call" function in DrupalMailchimp class in 7.x-3.x

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#28]
includes/mailchimp.inc

@levelos customized "callServer" for the 1.3 API to be drupal-ified. Need to do this again for 2.0 version [call()]

**Comment by unclegcb** [comment]
@levelos (bump)

**Comment by levelos** [comment]
Ref: 16fc53c75d5f97f2b7917afe8af8bf0087b5874c.
