### ISSUE TITLE
UI for creating mailchimp activity entities

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#3]

**Comment by unclegcb** [comment]
this exists but I need to learn the Ajax magic to make it a little more user-friendly, I think. currently you have to know the exact text of the entity type, bundle, and email property.

**Comment by levelos** [comment]
Those all need to be select lists. There are API calls for getting a list of entities. When an entity is selected, load up it's bundles. When a bundle is selected, load up the fields/props. Salesforce Mapping admin does some similar work. It's really tricky and takes some getting used to, so don't sweat it. I can knock it out and/or we can review when I'm hopefully back in.
