### ISSUE TITLE
Functionality question: unsubscribe on delete?

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#33]
@levelos @ruscoe 

I'm trying to decide about a behavior in the lists submodule. Currently, anytime an entity with a subscription field is deleted, we are unsubscribing that entity's email address from the corresponding list.

I'm thinking this might be overzealous. Perhaps it could be an option, but, for example, if I am merging RedHen contacts that have duplicate email addresses, this is going to unsubscribe them as part of the process, because one of the contacts gets deleted.

So is this option sensible to have around at all, or should I just delete it?

(hook_entity_delete in mailchimp_lists.module)

**Comment by levelos** [comment]
I think a field instance level setting defaulting to 'unsubscribe' makes
sense.

On Fri, Apr 4, 2014 at 8:59 AM, Gabe Carleton-Barnes <
notifications@github.com> wrote:

> @levelos https://github.com/levelos @ruscoe https://github.com/ruscoe
> 
> I'm trying to decide about a behavior in the lists submodule. Currently,
> anytime an entity with a subscription field is deleted, we are
> unsubscribing that entity's email address from the corresponding list.
> 
> I'm thinking this might be overzealous. Perhaps it could be an option,
> but, for example, if I am merging RedHen contacts that have duplicate email
> addresses, this is going to unsubscribe them as part of the process,
> because one of the contacts gets deleted.
> 
> So is this option sensible to have around at all, or should I just delete
> it?
> 
> (hook_entity_delete in mailchimp_lists.module)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/thinkshout/mailchimp/issues/33
> .

## 

Lev Tsypin, Partner

---

ThinkShout, Inc.
(503) 342 - 8044
thinkshout.com | twitter.com/levelos

**Comment by unclegcb** [comment]
simple enough to implement.
