### ISSUE TITLE
Update tests for 3.x branch

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#35]

**Comment by unclegcb** [comment]
@levelos Getting started on this and it's a much more significant re-write than I thought at first: the entirety of the testing infrastructure is based around Users and List Types from the 2.x model.

I could sink a lot of time into this.

Options:
- Sink a lot of time into it
- Postpone this feature
- Sink enough time to get 1 or 2 basic tests going to test, say the Async logic, and leave the rest for a future version

**Comment by ruscoe** [comment]
Added tests for mailchimp_lists and mailchimp_campaigns.

mailchimp_lists:
https://github.com/thinkshout/mailchimp/blob/7.x-3.x/modules/mailchimp_lists/tests/mailchimp_lists.test

mailchimp_campaigns:
https://github.com/thinkshout/mailchimp/blob/7.x-3.x/modules/mailchimp_campaign/tests/mailchimp_campaigns.test

Both can be run with the Testing module enabled by selecting MailChimp from the Development / Testing menu.
