### ISSUE TITLE
Ensure that subscription is only updated if merge values have changed

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#38]
I noticed that it was easy to have a mismatch between merge variables because we were only updating the Mailchimp values when the entity was edited through an interface that gave a value to the subscription field. VBO and other entity-based updates didn't trigger anything, so you could have your name changed through some custom UI and it wouldn't update your subscription on mailchimp.

I added code to fix this, but I'm concerned that it might be too much of a performance sacrifice: want to have a look?

92a6b6f261

**Comment by levelos** [comment]
Per code review, choices is always set with our metadata setter, but we still want to ensure we're only performing updates when needed.

Also a good time to rename `mailchimp_lists_process_subscribe_form_choices` to something like `mailchimp_lists_process_subscription()`.
