### ISSUE TITLE
refactor mailchimp_activity_page() to work with any entity type

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#4]

**Comment by unclegcb** [comment]
pushed this today. trying to wrap my head around the call to mailchimp_lists_get_available_lists(); using the current user's "list access" level to queue up the lists that will be checked for historical activity. Theoretically, this means that if a user had access to 2 of 3 lists and viewed an activity page for some entity that had history on all 3 lists, they would see a different list than a user who had access to all 3 lists viewing the same activity page.

I'm not sure this behavior is sensible, or that I'm correct in the way I'm reading this code.

**Comment by levelos** [comment]
Yeah, I thought of this too. I think we need to brainstorm a bit on this one. Most entities in question have a user property, so I think this is where we might want to look for non-anonymous use cases.

**Comment by unclegcb** [comment]
Well, I re-built this tool using the **listsForEmail** and realized in the process that there was probably going to be an unexpected behavioral implication, and I was right: users no longer see activity for lists that they have been unsubscribed from. This might be desirable in some cases but it seems like we really want to provide everything.

The rest of the user activity doesn't appear to be accessible through the API in any clean way. The best I can find is **campaignsForEmail** which lists all campaigns an address has been sent. We can extract the list from there, but if a user was a member of a list and never actually received an email from it, they won't show up here.

Thoughts?

**Comment by unclegcb** [comment]
extracting from "campaignsForEmail" might not be bad, since the tracked actions are only relevant if an email was actually sent. The only case where you'd be missing an action would be if a user unsubscribed from a list without ever receiving anything from a campaign using that list.

Interestingly, if you unsubscribe from a list and then later re-subscribe, the "unsubscribe" action is actually deleted from Mailchimp's history. No subscribe action appears in the history regardless.

**Comment by levelos** [comment]
Just did a bit 'o research and campaignsForEmail should work.

**Comment by unclegcb** [comment]
Implemented. I suspect there might be a cleaner way to do this and/or I got too cute with it. Pushed up to the branch, check the last method in mailchimp.module
