### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/mailchimp#6]
- [x] Review testing branch, clean up obvious to-dos and code style
- [x] Clean up any existing errors in the test output
- [x] Merge into 7.x-2.x
- [x] Ensure all test are passing!
- [x] Update documentation and project page with information about tests

@levelos any other pieces you want added here? please review & assign back to me.

**Comment by levelos** [comment]
Added a couple more, otherwise looks good.

**Comment by unclegcb** [comment]
Added testing documentation to the Readme. Going to create a separate task to update all the project page documentation before publishing the release.
