### ISSUE TITLE
error in validation if a merge fields with same name appear on the same page

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#60]
To reproduce, either create a signup page with multiple lists containing merge vars of the same name, or place a block on a signup page view. If two of the lists have merge vars of the same name, validation fails.

Most likely due to the form elements having the same name attribute. Possible solution is to prefix the name with a combination of view type (page or block) and unique id.

**Comment by unclegcb** [comment]
Fixed by using hook_blocks to generate unique form IDs for all forms.
