### ISSUE TITLE
Add a flag for setting permissions on signup forns

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#62]
@unclegcb, per our discussions, if we're going to offer granular settings for each signup form, we should add a checkbox for granting them by default to anon and auth roles. It seems that in some ways that nullifies having the granular settings in the first place since if you grant access to anon you grant access to all. Lets discuss ...

**Comment by unclegcb** [comment]
Stripped these permissions out: simple enough to revisit in the future if use cases are presented.
