### ISSUE TITLE
 Move "SITE CONTENT IMPORT" and "MERGE VARS" into input filter help

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#67]
It's a sibling to all the template sections rather than on it's own. I understand the goal of making it usable across all the content sections. One idea is just to move it into it's form section below the content sections. It also needs to messaged more clearly, E.g., use this widget to insert content tokens into the last content section you were just in. Also need to make clear that it will only work if the filter on the text area includes the mailchimp_campaign filter.

**Comment by levelos** [comment]
Per discussion, lets plan on moving this into the input filter help section for each applicable template section.

**Comment by ruscoe** [comment]
Created pull request: https://github.com/thinkshout/mailchimp/pull/77
