### ISSUE TITLE
Refactor _mailchimp_campaign_get_entity_import_form() to fix bug and improve efficiency

### ISSUE THREAD

**Issue by levelos** [thinkshout/mailchimp#80]
Two problems. Right now, the view modes are not getting updates when changing entity type.

Refactor to only process view mode options after an entity type is selected. Typically, add a condition around the form state entity type field, and then get view modes,

**Comment by ruscoe** [comment]
Fixed in pull request https://github.com/thinkshout/mailchimp/pull/77
