### ISSUE TITLE
Failed to load Mandrill PHP library

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp#85]
RB: https://redbooth.com/a/index.html#!/projects/329736/tasks/12940523
- [x] Update documentation with Mandrill PHP library installation instructions
- [x] Fix fatal PHP error when Mandrill PHP library is missing

**Comment by ruscoe** [comment]
@levelos can I get access to edit the Mandrill project page on d.o? I want to add this extra information: https://github.com/thinkshout/mandrill/commit/d7b1ae531cd50aa091461e1c4ce17a539a403f17

**Comment by levelos** [comment]
Done.

**Comment by ruscoe** [comment]
Updated. Thank you.

**Comment by ruscoe** [comment]
Fixed in commit https://github.com/thinkshout/mandrill/commit/619f311ac524da6906f294fcda1eaa3210566b47
